services:
  - type: web
    name: pushback
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PUSHBACK_API_KEY
        sync: false
